# Generated by Django 3.2.16 on 2022-10-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(editable=False, max_length=254, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('uid', models.CharField(editable=False, max_length=32)),
            ],
        ),
    ]
