# Generated by Django 3.2.16 on 2022-10-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='active',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='name',
            field=models.CharField(default='test', editable=False, max_length=256),
            preserve_default=False,
        ),
    ]
