# Generated by Django 3.2.16 on 2022-10-16 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_alter_newsletter_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='email',
            new_name='newsletter_email',
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='name',
            new_name='newsletter_name',
        ),
    ]
