# Generated by Django 3.2.16 on 2022-10-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='query_type',
            new_name='query',
        ),
    ]
