# Generated by Django 3.2.16 on 2022-10-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_response_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date_time']},
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='response_message',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='response_sent',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
