# Generated by Django 3.2.15 on 2022-09-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_custom_message',
            field=models.BooleanField(default=False),
        ),
    ]
