# Generated by Django 3.2.16 on 2023-02-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20230131_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
