# Generated by Django 3.2.16 on 2023-02-06 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_image_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='file_name',
        ),
    ]
